name: flutter_theme
description: A new Flutter package project.
version: 0.0.1
homepage:

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_extensions:
    git: https://github.com/mj12358/flutter-extensions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1